import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.7";

// This API is deliberately separate from Supabase Auth. It uses the app's own
// secure, httpOnly cookie sessions so the lightweight office-login workflow
// stays the same locally and when deployed.
const sql = postgres(Deno.env.get("SUPABASE_DB_URL")!, { max: 1, prepare: false, idle_timeout: 10 });
const PAYMENT_METHODS = ["Cash", "Bank", "bKash", "Nagad", "Card", "Other"];
const SESSION_DAYS = 7;
const SESSION_SECRET = Deno.env.get("SESSION_SECRET") || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const GITHUB_PAGES_ORIGIN = "https://arbanmti.github.io";
const encoder = new TextEncoder();
const loginAttempts = new Map<string, { count: number; startedAt: number; blockedUntil: number }>();

function now() { return new Date().toISOString(); }
function b64url(bytes: Uint8Array) { return btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function bytesFromB64url(value: string) {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - value.length % 4) % 4);
  return Uint8Array.from(atob(padded), (character) => character.charCodeAt(0));
}
function token(bytes = 32) { const value = new Uint8Array(bytes); crypto.getRandomValues(value); return b64url(value); }
async function hmac(value: string) {
  const key = await crypto.subtle.importKey("raw", encoder.encode(SESSION_SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return b64url(new Uint8Array(await crypto.subtle.sign("HMAC", key, encoder.encode(value))));
}
async function hashPassword(password: string) {
  const salt = new Uint8Array(16); crypto.getRandomValues(salt);
  const iterations = 210000;
  const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt, iterations, hash: "SHA-256" }, material, 256);
  return `pbkdf2$${iterations}$${b64url(salt)}$${b64url(new Uint8Array(bits))}`;
}
async function passwordMatches(password: string, stored: string) {
  const [scheme, iterationText, saltText, hashText] = String(stored).split("$");
  if (scheme !== "pbkdf2" || !saltText || !hashText) return false;
  const iterations = Number(iterationText);
  if (!Number.isSafeInteger(iterations) || iterations < 100000) return false;
  const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveBits"]);
  const actual = new Uint8Array(await crypto.subtle.deriveBits({ name: "PBKDF2", salt: bytesFromB64url(saltText), iterations, hash: "SHA-256" }, material, 256));
  const expected = bytesFromB64url(hashText);
  if (actual.length !== expected.length) return false;
  let difference = 0; for (let index = 0; index < actual.length; index += 1) difference |= actual[index] ^ expected[index];
  return difference === 0;
}
function cookies(request: Request) {
  const result: Record<string, string> = {};
  for (const part of (request.headers.get("cookie") || "").split(";")) {
    const index = part.indexOf("="); if (index < 1) continue;
    try { result[part.slice(0, index).trim()] = decodeURIComponent(part.slice(index + 1).trim()); } catch { /* malformed cookies are ignored */ }
  }
  return result;
}
function makeCookie(name: string, value: string, maxAge = 0) {
  const segments = [`${name}=${encodeURIComponent(value)}`, "Path=/", "HttpOnly", "SameSite=None", "Secure"];
  if (maxAge > 0) segments.push(`Max-Age=${maxAge}`); if (maxAge === -1) segments.push("Max-Age=0");
  return segments.join("; ");
}
function headers(contentType = "application/json; charset=utf-8") {
  return new Headers({
    "Content-Type": contentType, "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY",
    "Referrer-Policy": "no-referrer", "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
    "Cross-Origin-Opener-Policy": "same-origin", "Content-Security-Policy": "default-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'",
    "Access-Control-Allow-Origin": GITHUB_PAGES_ORIGIN, "Access-Control-Allow-Credentials": "true", "Access-Control-Allow-Headers": "content-type, x-csrf-token", "Access-Control-Allow-Methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS", "Vary": "Origin"
  });
}
function response(status: number, body: unknown, extra?: HeadersInit) {
  const result = headers(); for (const [key, value] of new Headers(extra || {})) result.append(key, value);
  return new Response(JSON.stringify(body), { status, headers: result });
}
function download(body: string, type: string, filename: string) {
  const result = headers(type); result.set("Content-Disposition", `attachment; filename="${filename}"`); return new Response(body, { status: 200, headers: result });
}
function problem(status: number, message: string) { return response(status, { error: message }); }
function error(message: string, status = 400): never { const value: any = new Error(message); value.status = status; throw value; }
function originIsTrusted(request: Request) {
  const origin = request.headers.get("origin");
  return !origin || origin === new URL(request.url).origin || origin === GITHUB_PAGES_ORIGIN;
}
function ip(request: Request) { return (request.headers.get("x-forwarded-for") || "unknown").split(",")[0].trim(); }
function loginAllowed(address: string) {
  const item = loginAttempts.get(address); const current = Date.now(); if (!item) return true;
  if (current - item.startedAt > 10 * 60 * 1000) { loginAttempts.delete(address); return true; }
  return item.blockedUntil <= current;
}
function registerFailedLogin(address: string) {
  const current = Date.now(); const item = loginAttempts.get(address) || { count: 0, startedAt: current, blockedUntil: 0 };
  if (current - item.startedAt > 10 * 60 * 1000) { item.count = 0; item.startedAt = current; }
  item.count += 1; if (item.count >= 5) item.blockedUntil = current + 15 * 60 * 1000; loginAttempts.set(address, item);
}
function today() {
  const pieces = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Dhaka", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts();
  const values = Object.fromEntries(pieces.filter((piece) => piece.type !== "literal").map((piece) => [piece.type, piece.value]));
  return `${values.year}-${values.month}-${values.day}`;
}
function nextMonth(month: string) { const [year, number] = month.split("-").map(Number); return new Date(Date.UTC(year, number, 1)).toISOString().slice(0, 7); }
function weekBounds() { const date = new Date(`${today()}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + (date.getUTCDay() === 0 ? -6 : 1 - date.getUTCDay())); const from = date.toISOString().slice(0, 10); date.setUTCDate(date.getUTCDate() + 7); return { from, to: date.toISOString().slice(0, 10) }; }
function string(value: unknown, name: string, limit: number) { if (typeof value !== "string" || !value.trim()) error(`${name} is required.`); const clean = value.trim(); if (clean.length > limit) error(`${name} is too long.`); return clean; }
function optional(value: unknown, name: string, limit: number) { if (value === undefined || value === null || value === "") return null; if (typeof value !== "string") error(`${name} is invalid.`); const clean = value.trim(); if (clean.length > limit) error(`${name} is too long.`); return clean || null; }
function validDate(value: unknown) { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(Date.parse(`${value}T00:00:00Z`))) error("A valid date is required."); return value; }
function paisa(value: unknown) { const input = String(value ?? "").trim(); if (!/^(?:0|[1-9]\d*)(?:\.\d{1,2})?$/.test(input)) error("Amount must be a valid positive number."); const [whole, decimal = ""] = input.split("."); const amount = BigInt(whole) * 100n + BigInt((decimal + "00").slice(0, 2)); if (amount <= 0n || amount > 9999999999n) error("Amount must be greater than zero and within the allowed limit."); return Number(amount); }
async function body(request: Request) { if (!request.headers.get("content-type")?.includes("application/json")) error("Request must use JSON.", 415); const text = await request.text(); if (text.length > 10 * 1024 * 1024) error("Request is too large.", 413); try { return text ? JSON.parse(text) : {}; } catch { error("Invalid JSON data."); } }
function dateOnly(value: unknown) { return value instanceof Date ? value.toISOString().slice(0, 10) : String(value).slice(0, 10); }
function expense(row: any) { return { ...row, id: Number(row.id), expense_type_id: Number(row.expense_type_id), expense_date: dateOnly(row.expense_date), amount_paisa: Number(row.amount_paisa), paid_to: row.paid_to || "", note: row.note || "" }; }
const EXPENSE_SELECT = `SELECT e.id, e.expense_date, e.expense_type_id, t.name AS expense_type, e.description, e.amount_paisa, e.payment_method, e.paid_to, e.note, e.external_ref, e.created_at, e.updated_at FROM expenses e JOIN expense_types t ON t.id=e.expense_type_id`;

async function auth(request: Request, csrf = false) {
  const sessionId = cookies(request).ledger_session; if (!sessionId) return null;
  const idHash = await hmac(sessionId);
  const rows: any[] = await sql.unsafe(`SELECT s.id_hash,s.csrf_token,s.expires_at,u.id AS user_id,u.username,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id_hash=$1`, [idHash]);
  const session = rows[0]; if (!session) return null;
  if (new Date(session.expires_at).getTime() <= Date.now()) { await sql.unsafe("DELETE FROM sessions WHERE id_hash=$1", [idHash]); return null; }
  if (csrf && (!originIsTrusted(request) || request.headers.get("x-csrf-token") !== session.csrf_token)) error("Your session could not be verified. Refresh the page and try again.", 403);
  await sql.unsafe("UPDATE sessions SET last_used_at=$1 WHERE id_hash=$2", [now(), idHash]);
  return { session, user: { id: Number(session.user_id), username: session.username, role: session.role } };
}
async function requireAuth(request: Request, csrf = false) { const value = await auth(request, csrf); if (!value) error("Please log in to continue.", 401); return value; }
function requireAdmin(value: any) { if (value.user.role !== "admin") error("Admin access is required.", 403); }
async function audit(db: any, userId: number, action: string, entity: string, entityId: unknown, detail?: unknown) { await db.unsafe("INSERT INTO audit_logs (user_id,action,entity_type,entity_id,details,created_at) VALUES ($1,$2,$3,$4,$5,$6)", [userId, action, entity, entityId == null ? null : String(entityId), detail ? JSON.stringify(detail) : null, now()]); }
async function sessionFor(userId: number) { const id = token(); const csrf = token(); const hash = await hmac(id); const stamp = now(); const expiry = new Date(Date.now() + SESSION_DAYS * 86400000).toISOString(); await sql.unsafe("INSERT INTO sessions (id_hash,user_id,csrf_token,expires_at,created_at,last_used_at) VALUES ($1,$2,$3,$4,$5,$6)", [hash, userId, csrf, expiry, stamp, stamp]); return { id, csrf }; }
async function activeType(id: number) { const rows: any[] = await sql.unsafe("SELECT id,name,is_active FROM expense_types WHERE id=$1", [id]); if (!rows[0] || !rows[0].is_active) error("Choose an active expense type."); return rows[0]; }
function validatedExpense(input: any) { const type = Number.parseInt(String(input.expense_type_id), 10); if (!Number.isSafeInteger(type) || type < 1) error("Expense type is required."); const payment = String(input.payment_method || ""); if (!PAYMENT_METHODS.includes(payment)) error("Payment method is required."); return { expense_date: validDate(input.expense_date), expense_type_id: type, description: string(input.description, "Description", 240), amount_paisa: paisa(input.amount), payment_method: payment, paid_to: optional(input.paid_to, "Paid To", 160), note: optional(input.note, "Note", 1000) }; }
function filters(url: URL) {
  const range = url.searchParams.get("range") || "this-month"; const values: unknown[] = []; const clauses: string[] = []; let from = ""; let to = "";
  if (range === "today") from = to = today(); else if (range === "this-week") { const bounds = weekBounds(); from = bounds.from; to = bounds.to; } else if (range === "this-month") { const month = today().slice(0, 7); from = `${month}-01`; to = nextMonth(month); } else if (range === "custom") { from = url.searchParams.get("from") || ""; to = url.searchParams.get("to") || ""; if (from) validDate(from); if (to) validDate(to); if (from && to && from > to) error("From date cannot be after To date."); } else if (range !== "all") error("Invalid date filter.");
  const add = (clause: string, value: unknown) => { values.push(value); clauses.push(clause.replace("?", `$${values.length}`)); };
  if (from) add("e.expense_date >= ?", from); if (to) add(range === "this-week" || range === "this-month" ? "e.expense_date < ?" : "e.expense_date <= ?", to);
  const search = (url.searchParams.get("q") || "").trim(); if (search) { const wildcard = `%${search.slice(0, 100)}%`; values.push(wildcard, wildcard, wildcard); const index = values.length - 2; clauses.push(`(e.description ILIKE $${index} OR COALESCE(e.paid_to,'') ILIKE $${index + 1} OR t.name ILIKE $${index + 2})`); }
  return { where: clauses.length ? ` WHERE ${clauses.join(" AND ")}` : "", values, range, from, to, search };
}
function csv(value: unknown) { const text = String(value ?? ""); return /[\",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
function uuid(value: unknown) { return typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }

const PASSENGER_STATUSES = ["New", "Submitted", "Processing", "Approved", "Complete", "Cancelled"];
const SUBMISSION_STATUSES = ["Submitted", "Processing", "Approved", "Complete", "Cancelled", "Returned"];
const PASSENGER_SELECT = `SELECT p.id,p.passenger_name,p.passport_number,p.country,p.agent_id,p.office_id,p.total_price_paisa,p.status,p.note,p.created_at,p.updated_at,a.name AS agent_name,o.name AS office_name,COALESCE((SELECT SUM(amount_paisa) FROM passenger_payments pp WHERE pp.passenger_id=p.id),0)::bigint AS received_paisa FROM passenger_files p JOIN agents a ON a.id=p.agent_id LEFT JOIN offices o ON o.id=p.office_id`;
const SUBMISSION_SELECT = `SELECT s.id,s.passenger_id,s.office_id,s.contract_number,s.submission_date,s.contract_amount_paisa,s.status,s.note,s.created_at,s.updated_at,p.passenger_name,p.passport_number,o.name AS office_name,COALESCE((SELECT SUM(amount_paisa) FROM office_payments op WHERE op.submission_id=s.id),0)::bigint AS paid_paisa FROM office_submissions s JOIN passenger_files p ON p.id=s.passenger_id JOIN offices o ON o.id=s.office_id`;

function id(value: unknown, name: string) { const result = Number.parseInt(String(value), 10); if (!Number.isSafeInteger(result) || result < 1) error(`${name} is required.`); return result; }
function optionalId(value: unknown, name: string) { if (value === undefined || value === null || value === "") return null; return id(value, name); }
function oneOf(value: unknown, options: string[], name: string) { const result = String(value || ""); if (!options.includes(result)) error(`${name} is invalid.`); return result; }
function partner(row: any) { return { ...row, id: Number(row.id), is_active: Boolean(row.is_active) }; }
function passenger(row: any) { const total = Number(row.total_price_paisa); const received = Number(row.received_paisa || 0); return { ...row, id: Number(row.id), agent_id: Number(row.agent_id), office_id: row.office_id === null ? null : Number(row.office_id), total_price_paisa: total, received_paisa: received, due_paisa: total - received }; }
function submission(row: any) { const amount = Number(row.contract_amount_paisa); const paid = Number(row.paid_paisa || 0); return { ...row, id: Number(row.id), passenger_id: Number(row.passenger_id), office_id: Number(row.office_id), contract_amount_paisa: amount, paid_paisa: paid, due_paisa: amount - paid }; }
function payment(row: any) { return { ...row, id: Number(row.id), amount_paisa: Number(row.amount_paisa) }; }
async function activePartner(table: "agents" | "offices", value: number, name: string) { const rows: any[] = await sql.unsafe(`SELECT id,is_active FROM ${table} WHERE id=$1`, [value]); if (!rows[0] || !rows[0].is_active) error(`Choose an active ${name}.`); }
function passengerData(input: any) { return { passenger_name: string(input.passenger_name, "Passenger name", 160), passport_number: string(input.passport_number, "Passport number", 40).toUpperCase(), country: string(input.country, "Country", 80), agent_id: id(input.agent_id, "Agent"), office_id: optionalId(input.office_id, "Office"), total_price_paisa: paisa(input.total_price), status: oneOf(input.status || "New", PASSENGER_STATUSES, "Passenger status"), note: optional(input.note, "Note", 1000) }; }
function submissionData(input: any) { return { passenger_id: id(input.passenger_id, "Passenger"), office_id: id(input.office_id, "Office"), contract_number: optional(input.contract_number, "Contract number", 80), submission_date: validDate(input.submission_date), contract_amount_paisa: paisa(input.contract_amount), status: oneOf(input.status || "Submitted", SUBMISSION_STATUSES, "Contract status"), note: optional(input.note, "Note", 1000) }; }
function paymentData(input: any) { const method = oneOf(input.payment_method, PAYMENT_METHODS, "Payment method"); return { payment_date: validDate(input.payment_date), amount_paisa: paisa(input.amount), payment_method: method, note: optional(input.note, "Note", 1000) }; }

async function handler(request: Request) {
  const url = new URL(request.url); const marker = "/functions/v1/ledger"; const rawPath = url.pathname;
  const path = rawPath.startsWith(marker) ? rawPath.slice(marker.length) || "/" : rawPath.startsWith("/ledger") ? rawPath.slice("/ledger".length) || "/" : rawPath;
  try {
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: headers() });
    if (request.method === "GET" && path === "/health") return response(200, { status: "ok" });
    if (request.method === "GET" && path === "/api/auth/status") {
      const users: any[] = await sql.unsafe("SELECT COUNT(*)::int AS count FROM users");
      if (Number(users[0].count) === 0) { const setup = cookies(request).ledger_setup || token(); return response(200, { needs_setup: true, setup_token: setup }, { "Set-Cookie": makeCookie("ledger_setup", setup, 900) }); }
      const current = await auth(request); return response(200, current ? { authenticated: true, user: current.user, csrf_token: current.session.csrf_token } : { authenticated: false });
    }
    if (request.method === "POST" && path === "/api/auth/setup") {
      const count: any[] = await sql.unsafe("SELECT COUNT(*)::int AS count FROM users"); if (Number(count[0].count)) return problem(409, "Initial setup has already been completed.");
      const input = await body(request); if (!originIsTrusted(request) || !input.setup_token || cookies(request).ledger_setup !== input.setup_token) return problem(403, "Setup verification failed. Refresh the page and try again.");
      const username = string(input.username, "Username", 50); if (!/^[A-Za-z0-9._-]{3,50}$/.test(username)) return problem(400, "Username must use 3–50 letters, numbers, dot, underscore, or dash."); const password = string(input.password, "Password", 200); if (password.length < 10) return problem(400, "Password must be at least 10 characters long.");
      const stamp = now(); const created: any[] = await sql.unsafe("INSERT INTO users (username,password_hash,role,created_at,updated_at) VALUES ($1,$2,'admin',$3,$4) RETURNING id,username,role", [username, await hashPassword(password), stamp, stamp]); const user = created[0]; await audit(sql, Number(user.id), "SETUP", "user", user.id); const session = await sessionFor(Number(user.id));
      return response(201, { message: "Admin account created.", user: { id: Number(user.id), username: user.username, role: user.role }, csrf_token: session.csrf }, { "Set-Cookie": makeCookie("ledger_session", session.id, SESSION_DAYS * 86400) });
    }
    if (request.method === "POST" && path === "/api/auth/login") {
      const address = ip(request); if (!loginAllowed(address)) return problem(429, "Too many failed attempts. Please wait 15 minutes before trying again."); const input = await body(request); const username = string(input.username, "Username", 50); const password = string(input.password, "Password", 200);
      const rows: any[] = await sql.unsafe("SELECT id,username,password_hash,role FROM users WHERE username=$1", [username]); const user = rows[0]; if (!user || !(await passwordMatches(password, user.password_hash))) { registerFailedLogin(address); return problem(401, "Invalid username or password."); }
      loginAttempts.delete(address); const session = await sessionFor(Number(user.id)); await audit(sql, Number(user.id), "LOGIN", "session", null); return response(200, { message: "Welcome back.", user: { id: Number(user.id), username: user.username, role: user.role }, csrf_token: session.csrf }, { "Set-Cookie": makeCookie("ledger_session", session.id, SESSION_DAYS * 86400) });
    }
    if (request.method === "POST" && path === "/api/auth/logout") { const current = await requireAuth(request, true); await sql.unsafe("DELETE FROM sessions WHERE id_hash=$1", [current.session.id_hash]); await audit(sql, current.user.id, "LOGOUT", "session", null); return response(200, { message: "Logged out." }, { "Set-Cookie": makeCookie("ledger_session", "", -1) }); }
    if (request.method === "GET" && path === "/api/dashboard") {
      await requireAuth(request); const day = today(); const month = day.slice(0, 7); const until = nextMonth(month);
      const [todaySum, monthSum, allSum, visaSum, recent] = await Promise.all([
        sql.unsafe("SELECT COALESCE(SUM(amount_paisa),0)::bigint AS total FROM expenses WHERE expense_date=$1", [day]), sql.unsafe("SELECT COALESCE(SUM(amount_paisa),0)::bigint AS total FROM expenses WHERE expense_date >= $1 AND expense_date < $2", [`${month}-01`, until]), sql.unsafe("SELECT COALESCE(SUM(amount_paisa),0)::bigint AS total FROM expenses"), sql.unsafe("SELECT COALESCE(SUM(e.amount_paisa),0)::bigint AS total FROM expenses e JOIN expense_types t ON t.id=e.expense_type_id WHERE t.name='Visa Fee'"), sql.unsafe(`${EXPENSE_SELECT} ORDER BY e.expense_date DESC,e.id DESC LIMIT 8`)
      ]);
      return response(200, { today_paisa: Number(todaySum[0].total), month_paisa: Number(monthSum[0].total), total_paisa: Number(allSum[0].total), visa_fee_paisa: Number(visaSum[0].total), recent: recent.map(expense) });
    }
    if (request.method === "GET" && path === "/api/expense-types") { await requireAuth(request); const all = url.searchParams.get("all") === "true"; const rows: any[] = await sql.unsafe(`SELECT id,name,is_active,created_at,updated_at FROM expense_types ${all ? "" : "WHERE is_active=true"} ORDER BY lower(name)`); return response(200, { items: rows.map((row) => ({ ...row, id: Number(row.id), is_active: Boolean(row.is_active) })) }); }
    if (request.method === "POST" && path === "/api/expense-types") { const current = await requireAuth(request, true); requireAdmin(current); const input = await body(request); const name = string(input.name, "Expense type", 80); const exists: any[] = await sql.unsafe("SELECT id FROM expense_types WHERE lower(name)=lower($1)", [name]); if (exists[0]) return problem(409, "This expense type already exists."); const created: any[] = await sql.unsafe("INSERT INTO expense_types (name,is_active,created_at,updated_at) VALUES ($1,true,$2,$3) RETURNING id,name,is_active,created_at,updated_at", [name, now(), now()]); await audit(sql, current.user.id, "CREATE", "expense_type", created[0].id, { name }); return response(201, { item: { ...created[0], id: Number(created[0].id), is_active: true } }); }
    const typeId = path.match(/^\/api\/expense-types\/(\d+)$/); if (request.method === "PATCH" && typeId) { const current = await requireAuth(request, true); requireAdmin(current); const input = await body(request); if (typeof input.is_active !== "boolean") return problem(400, "Active status is required."); const rows: any[] = await sql.unsafe("UPDATE expense_types SET is_active=$1,updated_at=$2 WHERE id=$3 RETURNING id,name,is_active,created_at,updated_at", [input.is_active, now(), Number(typeId[1])]); if (!rows[0]) return problem(404, "Expense type was not found."); await audit(sql, current.user.id, input.is_active ? "ACTIVATE" : "DEACTIVATE", "expense_type", typeId[1]); return response(200, { item: { ...rows[0], id: Number(rows[0].id), is_active: Boolean(rows[0].is_active) } }); }

    // Manpower master lists: agents and offices.
    if (request.method === "GET" && path === "/api/agents") { await requireAuth(request); const all = url.searchParams.get("all") === "true"; const rows: any[] = await sql.unsafe(`SELECT id,name,phone,is_active,created_at,updated_at FROM agents ${all ? "" : "WHERE is_active=true"} ORDER BY lower(name)`); return response(200, { items: rows.map(partner) }); }
    if (request.method === "POST" && path === "/api/agents") { const current = await requireAuth(request, true); requireAdmin(current); const input = await body(request); const name = string(input.name, "Agent name", 120); const exists: any[] = await sql.unsafe("SELECT id FROM agents WHERE lower(name)=lower($1)", [name]); if (exists[0]) return problem(409, "This agent already exists."); const rows: any[] = await sql.unsafe("INSERT INTO agents (name,phone,created_at,updated_at) VALUES ($1,$2,$3,$4) RETURNING id,name,phone,is_active,created_at,updated_at", [name, optional(input.phone, "Phone", 40), now(), now()]); await audit(sql,current.user.id,"CREATE","agent",rows[0].id,{name}); return response(201,{message:"Agent saved.",item:partner(rows[0])}); }
    const agentId = path.match(/^\/api\/agents\/(\d+)$/); if (request.method === "PATCH" && agentId) { const current=await requireAuth(request,true); requireAdmin(current); const input=await body(request); if(typeof input.is_active!=="boolean") return problem(400,"Active status is required."); const rows:any[]=await sql.unsafe("UPDATE agents SET is_active=$1,updated_at=$2 WHERE id=$3 RETURNING id,name,phone,is_active,created_at,updated_at",[input.is_active,now(),Number(agentId[1])]); if(!rows[0]) return problem(404,"Agent was not found."); await audit(sql,current.user.id,input.is_active?"ACTIVATE":"DEACTIVATE","agent",agentId[1]); return response(200,{item:partner(rows[0])}); }

    if (request.method === "GET" && path === "/api/offices") { await requireAuth(request); const all=url.searchParams.get("all")==="true"; const rows:any[]=await sql.unsafe(`SELECT id,name,contact_person,phone,address,is_active,created_at,updated_at FROM offices ${all ? "" : "WHERE is_active=true"} ORDER BY lower(name)`); return response(200,{items:rows.map(partner)}); }
    if (request.method === "POST" && path === "/api/offices") { const current=await requireAuth(request,true); requireAdmin(current); const input=await body(request); const name=string(input.name,"Office name",160); const exists:any[]=await sql.unsafe("SELECT id FROM offices WHERE lower(name)=lower($1)",[name]); if(exists[0]) return problem(409,"This office already exists."); const rows:any[]=await sql.unsafe("INSERT INTO offices (name,contact_person,phone,address,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,name,contact_person,phone,address,is_active,created_at,updated_at",[name,optional(input.contact_person,"Contact person",120),optional(input.phone,"Phone",40),optional(input.address,"Address",240),now(),now()]); await audit(sql,current.user.id,"CREATE","office",rows[0].id,{name}); return response(201,{message:"Office saved.",item:partner(rows[0])}); }
    const officeId = path.match(/^\/api\/offices\/(\d+)$/); if (request.method === "PATCH" && officeId) { const current=await requireAuth(request,true); requireAdmin(current); const input=await body(request); if(typeof input.is_active!=="boolean") return problem(400,"Active status is required."); const rows:any[]=await sql.unsafe("UPDATE offices SET is_active=$1,updated_at=$2 WHERE id=$3 RETURNING id,name,contact_person,phone,address,is_active,created_at,updated_at",[input.is_active,now(),Number(officeId[1])]); if(!rows[0]) return problem(404,"Office was not found."); await audit(sql,current.user.id,input.is_active?"ACTIVATE":"DEACTIVATE","office",officeId[1]); return response(200,{item:partner(rows[0])}); }

    if (request.method === "GET" && path === "/api/manpower/dashboard") { await requireAuth(request); const [fileCount,processing,price,received,officePaid,recent]:any=await Promise.all([sql.unsafe("SELECT COUNT(*)::int AS total FROM passenger_files"),sql.unsafe("SELECT COUNT(*)::int AS total FROM passenger_files WHERE status='Processing'"),sql.unsafe("SELECT COALESCE(SUM(total_price_paisa),0)::bigint AS total FROM passenger_files"),sql.unsafe("SELECT COALESCE(SUM(amount_paisa),0)::bigint AS total FROM passenger_payments"),sql.unsafe("SELECT COALESCE(SUM(amount_paisa),0)::bigint AS total FROM office_payments"),sql.unsafe(`${PASSENGER_SELECT} ORDER BY p.updated_at DESC,p.id DESC LIMIT 8`)]); const totalPrice=Number(price[0].total); const totalReceived=Number(received[0].total); return response(200,{total_files:Number(fileCount[0].total),processing_files:Number(processing[0].total),total_price_paisa:totalPrice,total_received_paisa:totalReceived,total_due_paisa:totalPrice-totalReceived,office_paid_paisa:Number(officePaid[0].total),recent:recent.map(passenger)}); }

    if (request.method === "GET" && path === "/api/passengers") { await requireAuth(request); const values:unknown[]=[]; const clauses:string[]=[]; const add=(clause:string,value:unknown)=>{values.push(value);clauses.push(clause.replace("?",`$${values.length}`));}; const status=url.searchParams.get("status")||""; if(status) add("p.status=?",oneOf(status,PASSENGER_STATUSES,"Passenger status")); const agent=url.searchParams.get("agent_id")||""; if(agent) add("p.agent_id=?",id(agent,"Agent")); const search=(url.searchParams.get("q")||"").trim(); if(search){const wildcard=`%${search.slice(0,100)}%`;values.push(wildcard,wildcard,wildcard,wildcard);const offset=values.length-3;clauses.push(`(p.passenger_name ILIKE $${offset} OR p.passport_number ILIKE $${offset+1} OR p.country ILIKE $${offset+2} OR a.name ILIKE $${offset+3})`);} const where=clauses.length?` WHERE ${clauses.join(" AND ")}`:""; const rows:any[]=await sql.unsafe(`${PASSENGER_SELECT}${where} ORDER BY p.updated_at DESC,p.id DESC LIMIT 500`,values); return response(200,{items:rows.map(passenger)}); }
    if (request.method === "POST" && path === "/api/passengers") { const current=await requireAuth(request,true); const data=passengerData(await body(request)); await activePartner("agents",data.agent_id,"agent"); if(data.office_id) await activePartner("offices",data.office_id,"office"); const existing:any[]=await sql.unsafe("SELECT id FROM passenger_files WHERE upper(passport_number)=upper($1)",[data.passport_number]); if(existing[0]) return problem(409,"This passport number already has a passenger file."); const stamp=now(); const made:any[]=await sql.unsafe("INSERT INTO passenger_files (passenger_name,passport_number,country,agent_id,office_id,total_price_paisa,status,note,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id",[data.passenger_name,data.passport_number,data.country,data.agent_id,data.office_id,data.total_price_paisa,data.status,data.note,stamp,stamp]); await audit(sql,current.user.id,"CREATE","passenger",made[0].id,{passport_number:data.passport_number}); const rows:any[]=await sql.unsafe(`${PASSENGER_SELECT} WHERE p.id=$1`,[made[0].id]); return response(201,{message:"Passenger file saved.",item:passenger(rows[0])}); }
    const passengerId=path.match(/^\/api\/passengers\/(\d+)$/); if(passengerId && request.method==="GET"){await requireAuth(request);const rows:any[]=await sql.unsafe(`${PASSENGER_SELECT} WHERE p.id=$1`,[Number(passengerId[1])]);if(!rows[0])return problem(404,"Passenger file was not found.");const [payments,submissions]:any=await Promise.all([sql.unsafe("SELECT id,payment_date,amount_paisa,payment_method,note,created_at FROM passenger_payments WHERE passenger_id=$1 ORDER BY payment_date DESC,id DESC",[Number(passengerId[1])]),sql.unsafe(`${SUBMISSION_SELECT} WHERE s.passenger_id=$1 ORDER BY s.submission_date DESC,s.id DESC`,[Number(passengerId[1])])]);return response(200,{item:passenger(rows[0]),payments:payments.map(payment),submissions:submissions.map(submission)});}
    if(passengerId && request.method==="PUT"){const current=await requireAuth(request,true);const data=passengerData(await body(request));await activePartner("agents",data.agent_id,"agent");if(data.office_id)await activePartner("offices",data.office_id,"office");const duplicate:any[]=await sql.unsafe("SELECT id FROM passenger_files WHERE upper(passport_number)=upper($1) AND id<>$2",[data.passport_number,Number(passengerId[1])]);if(duplicate[0])return problem(409,"This passport number already has a passenger file.");const changed:any[]=await sql.unsafe("UPDATE passenger_files SET passenger_name=$1,passport_number=$2,country=$3,agent_id=$4,office_id=$5,total_price_paisa=$6,status=$7,note=$8,updated_at=$9 WHERE id=$10 RETURNING id",[data.passenger_name,data.passport_number,data.country,data.agent_id,data.office_id,data.total_price_paisa,data.status,data.note,now(),Number(passengerId[1])]);if(!changed[0])return problem(404,"Passenger file was not found.");await audit(sql,current.user.id,"UPDATE","passenger",passengerId[1]);const rows:any[]=await sql.unsafe(`${PASSENGER_SELECT} WHERE p.id=$1`,[Number(passengerId[1])]);return response(200,{message:"Passenger file updated.",item:passenger(rows[0])});}
    const passengerPayment=path.match(/^\/api\/passengers\/(\d+)\/payments$/); if(passengerPayment && request.method==="POST"){const current=await requireAuth(request,true);const passengerKey=Number(passengerPayment[1]);const exists:any[]=await sql.unsafe("SELECT id FROM passenger_files WHERE id=$1",[passengerKey]);if(!exists[0])return problem(404,"Passenger file was not found.");const data=paymentData(await body(request));const rows:any[]=await sql.unsafe("INSERT INTO passenger_payments (passenger_id,payment_date,amount_paisa,payment_method,note,created_at) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,payment_date,amount_paisa,payment_method,note,created_at",[passengerKey,data.payment_date,data.amount_paisa,data.payment_method,data.note,now()]);await audit(sql,current.user.id,"RECEIVE_PAYMENT","passenger",passengerKey,{amount_paisa:data.amount_paisa});return response(201,{message:"Passenger payment saved.",item:payment(rows[0])});}

    if(request.method==="GET" && path==="/api/office-submissions"){await requireAuth(request);const rows:any[]=await sql.unsafe(`${SUBMISSION_SELECT} ORDER BY s.submission_date DESC,s.id DESC LIMIT 500`);return response(200,{items:rows.map(submission)});}
    if(request.method==="POST" && path==="/api/office-submissions"){const current=await requireAuth(request,true);const data=submissionData(await body(request));const passengerRows:any[]=await sql.unsafe("SELECT id FROM passenger_files WHERE id=$1",[data.passenger_id]);if(!passengerRows[0])return problem(404,"Passenger file was not found.");await activePartner("offices",data.office_id,"office");const stamp=now();const made:any[]=await sql.unsafe("INSERT INTO office_submissions (passenger_id,office_id,contract_number,submission_date,contract_amount_paisa,status,note,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id",[data.passenger_id,data.office_id,data.contract_number,data.submission_date,data.contract_amount_paisa,data.status,data.note,stamp,stamp]);await audit(sql,current.user.id,"CREATE","office_submission",made[0].id,{passenger_id:data.passenger_id,office_id:data.office_id});const rows:any[]=await sql.unsafe(`${SUBMISSION_SELECT} WHERE s.id=$1`,[made[0].id]);return response(201,{message:"Office contract saved.",item:submission(rows[0])});}
    const submissionId=path.match(/^\/api\/office-submissions\/(\d+)$/);if(submissionId && request.method==="GET"){await requireAuth(request);const rows:any[]=await sql.unsafe(`${SUBMISSION_SELECT} WHERE s.id=$1`,[Number(submissionId[1])]);if(!rows[0])return problem(404,"Office contract was not found.");const payments:any[]=await sql.unsafe("SELECT id,payment_date,amount_paisa,payment_method,note,created_at FROM office_payments WHERE submission_id=$1 ORDER BY payment_date DESC,id DESC",[Number(submissionId[1])]);return response(200,{item:submission(rows[0]),payments:payments.map(payment)});}
    if(submissionId && request.method==="PUT"){const current=await requireAuth(request,true);const data=submissionData(await body(request));const passengerRows:any[]=await sql.unsafe("SELECT id FROM passenger_files WHERE id=$1",[data.passenger_id]);if(!passengerRows[0])return problem(404,"Passenger file was not found.");await activePartner("offices",data.office_id,"office");const changed:any[]=await sql.unsafe("UPDATE office_submissions SET passenger_id=$1,office_id=$2,contract_number=$3,submission_date=$4,contract_amount_paisa=$5,status=$6,note=$7,updated_at=$8 WHERE id=$9 RETURNING id",[data.passenger_id,data.office_id,data.contract_number,data.submission_date,data.contract_amount_paisa,data.status,data.note,now(),Number(submissionId[1])]);if(!changed[0])return problem(404,"Office contract was not found.");await audit(sql,current.user.id,"UPDATE","office_submission",submissionId[1]);const rows:any[]=await sql.unsafe(`${SUBMISSION_SELECT} WHERE s.id=$1`,[Number(submissionId[1])]);return response(200,{message:"Office contract updated.",item:submission(rows[0])});}
    const officePayment=path.match(/^\/api\/office-submissions\/(\d+)\/payments$/);if(officePayment && request.method==="POST"){const current=await requireAuth(request,true);const submissionKey=Number(officePayment[1]);const exists:any[]=await sql.unsafe("SELECT id FROM office_submissions WHERE id=$1",[submissionKey]);if(!exists[0])return problem(404,"Office contract was not found.");const data=paymentData(await body(request));const rows:any[]=await sql.unsafe("INSERT INTO office_payments (submission_id,payment_date,amount_paisa,payment_method,note,created_at) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,payment_date,amount_paisa,payment_method,note,created_at",[submissionKey,data.payment_date,data.amount_paisa,data.payment_method,data.note,now()]);await audit(sql,current.user.id,"OFFICE_PAYMENT","office_submission",submissionKey,{amount_paisa:data.amount_paisa});return response(201,{message:"Office payment saved.",item:payment(rows[0])});}

    if(request.method==="GET" && path==="/api/manpower/reports/monthly"){await requireAuth(request);const month=url.searchParams.get("month")||today().slice(0,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))return problem(400,"Choose a valid month.");const params=[`${month}-01`,nextMonth(month)];const [passengerReceived,officePaid,totalPrice,totalReceived,active,rows]:any=await Promise.all([sql.unsafe("SELECT COALESCE(SUM(amount_paisa),0)::bigint AS total FROM passenger_payments WHERE payment_date >= $1 AND payment_date < $2",params),sql.unsafe("SELECT COALESCE(SUM(amount_paisa),0)::bigint AS total FROM office_payments WHERE payment_date >= $1 AND payment_date < $2",params),sql.unsafe("SELECT COALESCE(SUM(total_price_paisa),0)::bigint AS total FROM passenger_files"),sql.unsafe("SELECT COALESCE(SUM(amount_paisa),0)::bigint AS total FROM passenger_payments"),sql.unsafe("SELECT COUNT(*)::int AS total FROM passenger_files WHERE status NOT IN ('Complete','Cancelled')"),sql.unsafe(`${PASSENGER_SELECT} ORDER BY p.updated_at DESC,p.id DESC LIMIT 500`)]);return response(200,{month,passenger_received_paisa:Number(passengerReceived[0].total),office_paid_paisa:Number(officePaid[0].total),total_due_paisa:Number(totalPrice[0].total)-Number(totalReceived[0].total),active_files:Number(active[0].total),items:rows.map(passenger)});}
    if (request.method === "GET" && path === "/api/expenses") { await requireAuth(request); const filter = filters(url); const rows: any[] = await sql.unsafe(`${EXPENSE_SELECT}${filter.where} ORDER BY e.expense_date DESC,e.id DESC LIMIT 500`, filter.values); const totals: any[] = await sql.unsafe(`SELECT COALESCE(SUM(e.amount_paisa),0)::bigint AS total FROM expenses e JOIN expense_types t ON t.id=e.expense_type_id${filter.where}`, filter.values); return response(200, { items: rows.map(expense), total_paisa: Number(totals[0].total), filter: { range: filter.range, from: filter.from, to: filter.to, search: filter.search } }); }
    if (request.method === "POST" && path === "/api/expenses") { const current = await requireAuth(request, true); const data = validatedExpense(await body(request)); await activeType(data.expense_type_id); const stamp = now(); const created: any[] = await sql.unsafe("INSERT INTO expenses (expense_date,expense_type_id,description,amount_paisa,payment_method,paid_to,note,external_ref,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id", [data.expense_date,data.expense_type_id,data.description,data.amount_paisa,data.payment_method,data.paid_to,data.note,crypto.randomUUID(),stamp,stamp]); await audit(sql,current.user.id,"CREATE","expense",created[0].id); const rows: any[] = await sql.unsafe(`${EXPENSE_SELECT} WHERE e.id=$1`,[created[0].id]); return response(201,{message:"Expense saved successfully.",item:expense(rows[0])}); }
    const expenseId = path.match(/^\/api\/expenses\/(\d+)$/);
    if (expenseId && request.method === "GET") { await requireAuth(request); const rows: any[] = await sql.unsafe(`${EXPENSE_SELECT} WHERE e.id=$1`, [Number(expenseId[1])]); if (!rows[0]) return problem(404,"Expense was not found."); return response(200,{item:expense(rows[0])}); }
    if (expenseId && request.method === "PUT") { const current=await requireAuth(request,true); const data=validatedExpense(await body(request)); await activeType(data.expense_type_id); const rows:any[]=await sql.unsafe("UPDATE expenses SET expense_date=$1,expense_type_id=$2,description=$3,amount_paisa=$4,payment_method=$5,paid_to=$6,note=$7,updated_at=$8 WHERE id=$9 RETURNING id",[data.expense_date,data.expense_type_id,data.description,data.amount_paisa,data.payment_method,data.paid_to,data.note,now(),Number(expenseId[1])]); if(!rows[0]) return problem(404,"Expense was not found."); await audit(sql,current.user.id,"UPDATE","expense",expenseId[1]); const item:any[]=await sql.unsafe(`${EXPENSE_SELECT} WHERE e.id=$1`,[Number(expenseId[1])]); return response(200,{message:"Expense updated successfully.",item:expense(item[0])}); }
    if (expenseId && request.method === "DELETE") { const current=await requireAuth(request,true); const existing:any[]=await sql.unsafe(`${EXPENSE_SELECT} WHERE e.id=$1`,[Number(expenseId[1])]); if(!existing[0]) return problem(404,"Expense was not found."); await sql.begin(async (tx:any)=>{ await audit(tx,current.user.id,"DELETE","expense",expenseId[1],{expense_date:dateOnly(existing[0].expense_date),amount_paisa:Number(existing[0].amount_paisa),description:existing[0].description}); await tx.unsafe("DELETE FROM expenses WHERE id=$1",[Number(expenseId[1])]); }); return response(200,{message:"Expense deleted."}); }
    if (request.method === "GET" && path === "/api/reports/monthly") { await requireAuth(request); const month=url.searchParams.get("month") || today().slice(0,7); if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)) return problem(400,"Choose a valid month."); const params=[`${month}-01`,nextMonth(month)]; const [sum,visa,payments,rows]:any=await Promise.all([sql.unsafe("SELECT COALESCE(SUM(e.amount_paisa),0)::bigint AS total FROM expenses e WHERE e.expense_date >= $1 AND e.expense_date < $2",params),sql.unsafe("SELECT COALESCE(SUM(e.amount_paisa),0)::bigint AS total FROM expenses e JOIN expense_types t ON t.id=e.expense_type_id WHERE e.expense_date >= $1 AND e.expense_date < $2 AND t.name='Visa Fee'",params),sql.unsafe("SELECT e.payment_method,COALESCE(SUM(e.amount_paisa),0)::bigint AS total FROM expenses e WHERE e.expense_date >= $1 AND e.expense_date < $2 GROUP BY e.payment_method",params),sql.unsafe(`${EXPENSE_SELECT} WHERE e.expense_date >= $1 AND e.expense_date < $2 ORDER BY e.expense_date DESC,e.id DESC`,params)]); const payment_totals:any=Object.fromEntries(PAYMENT_METHODS.map((method)=>[method,0])); payments.forEach((item:any)=>payment_totals[item.payment_method]=Number(item.total)); return response(200,{month,total_paisa:Number(sum[0].total),visa_fee_paisa:Number(visa[0].total),payment_totals,items:rows.map(expense)}); }
    if (request.method === "GET" && path === "/api/backup") { await requireAuth(request); const format=url.searchParams.get("format") || "json"; if(!["json","csv"].includes(format)) return problem(400,"Backup format must be JSON or CSV."); const [types,rows]:any=await Promise.all([sql.unsafe("SELECT name,is_active,created_at,updated_at FROM expense_types ORDER BY id"),sql.unsafe(`${EXPENSE_SELECT} ORDER BY e.id`)]); const items=rows.map((row:any)=>{const item=expense(row);return {external_ref:item.external_ref,expense_date:item.expense_date,expense_type:item.expense_type,description:item.description,amount_paisa:item.amount_paisa,payment_method:item.payment_method,paid_to:item.paid_to,note:item.note,created_at:item.created_at,updated_at:item.updated_at};}); const stamp=today(); if(format==="json") return download(JSON.stringify({backup_version:1,application:"Office Expense Ledger",exported_at:now(),expense_types:types,expenses:items},null,2),"application/json; charset=utf-8",`office-expense-ledger-${stamp}.json`); const lines=items.map((item:any)=>[item.expense_date,item.expense_type,item.description,(item.amount_paisa/100).toFixed(2),item.payment_method,item.paid_to,item.note,item.external_ref].map(csv).join(",")); return download(`\uFEFFDate,Expense Type,Description,Amount BDT,Payment Method,Paid To,Note,Reference\r\n${lines.join("\r\n")}\r\n`,"text/csv; charset=utf-8",`office-expense-ledger-${stamp}.csv`); }
    if (request.method === "POST" && path === "/api/backup/import") { const current=await requireAuth(request,true); requireAdmin(current); const input=await body(request); if(!input || input.backup_version!==1 || !Array.isArray(input.expenses) || input.expenses.length>50000) return problem(400,"This is not a valid Office Expense Ledger JSON backup."); const allTypes=Array.isArray(input.expense_types)?input.expense_types:[]; let imported=0,skipped=0; await sql.begin(async(tx:any)=>{const known:any[]=await tx.unsafe("SELECT id,name FROM expense_types"); const map=new Map(known.map((item:any)=>[String(item.name).toLowerCase(),Number(item.id)])); const wanted=[...allTypes,...input.expenses.map((item:any)=>({name:item.expense_type,is_active:true}))]; for(const item of wanted){const name=string(item.name,"Expense type",80);const key=name.toLowerCase();if(!map.has(key)){const inserted:any[]=await tx.unsafe("INSERT INTO expense_types (name,is_active,created_at,updated_at) VALUES ($1,$2,$3,$4) RETURNING id",[name,item.is_active!==false,now(),now()]);map.set(key,Number(inserted[0].id));}} for(const item of input.expenses){if(!uuid(item.external_ref)) error("Backup contains an invalid expense reference.");const amount=Number(item.amount_paisa);if(!Number.isSafeInteger(amount)||amount<=0||amount>9999999999) error("Backup contains an invalid amount.");if(!PAYMENT_METHODS.includes(item.payment_method)) error("Backup contains an invalid payment method.");const typeName=string(item.expense_type,"Expense type",80);const exists:any[]=await tx.unsafe("SELECT id FROM expenses WHERE external_ref=$1",[item.external_ref]);if(exists[0]){skipped++;continue;}await tx.unsafe("INSERT INTO expenses (expense_date,expense_type_id,description,amount_paisa,payment_method,paid_to,note,external_ref,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[validDate(item.expense_date),map.get(typeName.toLowerCase()),string(item.description,"Description",240),amount,item.payment_method,optional(item.paid_to,"Paid To",160),optional(item.note,"Note",1000),item.external_ref,typeof item.created_at==="string"?item.created_at:now(),typeof item.updated_at==="string"?item.updated_at:now()]);imported++;} await audit(tx,current.user.id,"IMPORT","backup",null,{imported,skipped});}); return response(200,{message:`Backup restored: ${imported} added, ${skipped} duplicate entries skipped.`,imported,skipped}); }
    if (request.method === "POST" && path === "/api/settings/password") { const current=await requireAuth(request,true); const input=await body(request); const oldPassword=string(input.current_password,"Current password",200); const newPassword=string(input.new_password,"New password",200); if(newPassword.length<10) return problem(400,"New password must be at least 10 characters long."); const row:any[]=await sql.unsafe("SELECT password_hash FROM users WHERE id=$1",[current.user.id]); if(!(await passwordMatches(oldPassword,row[0].password_hash))) return problem(401,"Current password is incorrect."); await sql.unsafe("UPDATE users SET password_hash=$1,updated_at=$2 WHERE id=$3",[await hashPassword(newPassword),now(),current.user.id]); await sql.unsafe("DELETE FROM sessions WHERE user_id=$1 AND id_hash<>$2",[current.user.id,current.session.id_hash]); await audit(sql,current.user.id,"PASSWORD_CHANGE","user",current.user.id); return response(200,{message:"Password updated. Other devices have been logged out."}); }
    return problem(404,"Page or API endpoint was not found.");
  } catch (caught: any) { console.error(caught?.message || "request failed"); const status=Number(caught?.status) || 500; return problem(status,status>=500?"Something went wrong. Please try again.":caught.message); }
}

Deno.serve(handler);
